// Generated by https://quicktype.io

export interface SummonerApiResponse {
    id: string;
    accountId: string;
    puuid: string;
    name: string;
    profileIconId: number;
    revisionDate: number;
    summonerLevel: number;
}
